// <auto-generated />
namespace Music.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NameMethodAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameMethodAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202011241904341_NameMethodAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
